---
services:
  ts-homepage:
    image: tailscale/tailscale:latest
    container_name: ts-homepage
    hostname: homepage
    environment:
      - TS_AUTHKEY=${TSKEY_AUTH}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_HOSTNAME=home
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_SERVE_CONFIG=/config/homepage.json
    volumes:
      - ${APPDATA}/ts-homepage/state:/var/lib/tailscale
      - ${APPDATA}/ts-homepage/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    volumes:
      - ${APPDATA}/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    depends_on:
      - ts-homepage
    network_mode: service:ts-homepage
volumes:
  ts-homepage:
    driver: local
